apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notifications.fullname" . }}
  labels:
    {{ include "notifications.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "notifications.name" .}}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "notifications.config.checksum" . }}
      {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: notifications
        app.kubernetes.io/instance: {{ .Release.Name }}
        #{{ include "notifications.labels" . | nindent 8 }}
        #{{- with .Values.podLabels }}
        #{{ toYaml . | nindent 8 }}
        #{{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "notifications.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{ toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/tomee/bin/catalina.sh
            - run
          env:
            - name: NS_PROPERTIES_YAML_PATH
              value: /etc/dataone/notification-service/properties.yaml
            - name: CATALINA_OPTS
              value: {{ join " " .Values.tomcat.extraCatalinaOpts }}
                      {{- if .Values.tomcat.jmxEnabled }}
                        {{- if .Values.tomcat.extraCatalinaOpts }}
                          {{- printf " " }}
                        {{- end }}
                        {{- join " " .Values.tomcat.jmxCatalinaOpts }}
                      {{- end }}{{- printf " " -}}
                      -Dlog4j2.configurationFile=/etc/dataone/notification-service/log4j2-k8s.yaml
            {{- $pgSecret :=  required "ns.database.existingSecret IS REQUIRED" .Values.ns.database.existingSecret }}
            - name: NS_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: username
            - name: NS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: password
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.tomcat.jmxEnabled }}
            - containerPort: {{ .Values.tomcat.jmxPort }}
              name: jmx
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- omit .Values.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.extraVolumeMounts }}
            {{- tpl (toYaml .Values.extraVolumeMounts) . | nindent 12 }}
            {{- end }}
            - mountPath: /etc/dataone/notification-service
              name: {{ .Release.Name }}-config-volume
              readOnly: true
      volumes:
        {{- if .Values.extraVolumes }}
        {{- tpl (toYaml .Values.extraVolumes) . | nindent 8 }}
        {{- end }}
        - name: {{ .Release.Name }}-config-volume
          configMap:
            name: {{ .Release.Name }}-notifications-configfiles
            defaultMode: 0644

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
