## override values.yaml with values to use for running on a local Rancher Desktop cluster
##
## example:
##
##  helm upgrade --install ns --debug -n notifications --create-namespace \
##                          -f ./helm/examples/values-dev-cluster-ns-example.yaml \
##                          oci://ghcr.io/dataoneorg/charts/notifications --version [version]
##
## ...or to install from local helm chart code, replace:
##   oci://ghcr.io/dataoneorg/charts/notifications --version [version]
## with:
##   ./helm
##
## see values.yaml for full documentation on the following parameters
##
ns:
  logLevel: debug
  auth:
    api:
      baseUrl: https://cn-sandbox.test.dataone.org/cn/v2

  database:
    jdbcHost: nsdb-cnpg-rw
    existingSecret: nsdb-cnpg-app

ingress:
  hosts:
    - host: notifications.local
      paths:
        - path: /
          pathType: Prefix
    ## After applying the above, add this entry to /etc/hosts file:
    ##
    ##   $ echo "127.0.0.1    notifications.local" | sudo tee -a /etc/hosts
    ##
    ## Now you can access the notifications service at:
    ##   http://notifications.local/notifications/metrics/ping
