## override values.yaml with values to use for running on a local Rancher Desktop cluster
##
## example:
##
##  helm upgrade --install ns --debug -n notifications --create-namespace \
##                          -f ./helm/examples/values-dev-cluster-ns-example.yaml \
##                          oci://ghcr.io/dataoneorg/charts/notifications --version [version]
##
## ...or to install from local helm chart code, replace:
##   oci://ghcr.io/dataoneorg/charts/notifications --version [version]
## with:
##   ./helm
##
## see values.yaml for full documentation on the following parameters
##
ns:
  logLevel: debug
  auth:
    api:
      baseUrl: https://cn-sandbox.test.dataone.org/cn/v2

  database:
    jdbcHost: nsdb-cnpg-rw
    existingSecret: nsdb-cnpg-app

ingress:
  hosts:
    - host: notifications.local
      paths:
        - path: /
          pathType: Prefix
    ## After applying the above, add this entry to /etc/hosts file:
    ##
    ##   $ echo "127.0.0.1    notifications.local" | sudo tee -a /etc/hosts
    ##
    ## Now you can access the notifications service at:
    ##   http://notifications.local/notifications/metrics/ping

# to add
rabbitmq:
  host: ns-rmq-4-1-3
  port: 5672
  username: default_user_oH3nQSTlAJFDabamw4u
  password: oQFSI9eM9rJ43p2E_K6YkxwrRu6aTkqh
  virtualHost: /
  queueName: notification.subscription.events
  prefetchCount: 25
  connectionName: notifications-consumer
  requeueOnError: true

## To rename/repurpose
idxworker:
  ## @param idxworker.rabbitmqHostname RMQ host to be called by indexer. Leave blank to autopopulate
  ## from the bundled rabbitmq operator installation (if rabbitmq.enabled)
  ##
  rabbitmqHostname: ""

  ## @param idxworker.rabbitmqHostPort RMQ port to be called by indexer. (Doesn't set rmq's port!)
  ## Only tells the indexer which port to use in the connection string.
  ##
  rabbitmqHostPort: "5672"

  ## @param idxworker.rabbitmqUsername The username needed for rabbitmq access. Leave blank to autopopulate
  ## from 'idxworker.rabbitmqSecret'
  ##
  rabbitmqUsername: ""

  ## @param idxworker.rabbitmqSecret Secret holding rmq credentials. Leave blank to autopopulate
  ## from the bundled rabbitmq operator installation (if rabbitmq.enabled)
  ##
  rabbitmqSecret: ""

  ## @param idxworker.rabbitmqUserKey key associated with rabbitmq username in existing secret
  ##
  rabbitmqUserKey: "username"

  ## @param idxworker.rabbitmqPasswordKey key associated with rabbitmq password in existing secret
  ##
  rabbitmqPasswordKey: "password"
