## override values.yaml with values to use for running on the NCEAS dev cluster
##
## example:
##
##  helm upgrade --install ns --debug -n notifications \
##                          -f ./helm/examples/values-dev-cluster-ns-example.yaml \
##                          oci://ghcr.io/dataoneorg/charts/notifications --version [version]
##
## ...or to install from local helm chart code, replace:
##   oci://ghcr.io/dataoneorg/charts/notifications --version [version]
## with:
##   ./helm
##
## see values.yaml for full documentation on the following parameters
##

ns:
  logLevel: debug
  auth:
    api:
      baseUrl: https://cn-sandbox.test.dataone.org/cn/v2

  ## Assuming your CNPG helm release name is 'nsdb':
  database:
    jdbcHost: nsdb-cnpg-rw
    existingSecret: nsdb-cnpg-app
image:
    repository: ghcr.io/dataoneorg/notification-service
    pullPolicy: Always
tomcat:
  jmxEnabled: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 128Mi

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: &hostname notifications.test.dataone.org
      paths:
        - path: /
          pathType: Prefix
        - path: /notifications/v1/eventhandler
          pathType: Prefix
          backend:
            serviceName: null-service
            servicePort: 80
  tls:
    - hosts:
        - *hostname
      secretName: ingress-tls-cert

nsconsumer:
  image:
    repository: ghcr.io/dataoneorg/notification-consumer
    tag: feature-5-eventhandler
    pullPolicy: Always

emailUtil:
  # @section emailUtil.auth Configuration for SMTP authentication.
  auth:
    # @param emailUtil.auth.enabled Enable or disable SMTP authentication.
    enabled: true
    # @param emailUtil.auth.existingSecret Secret holding SMTP credentials. This won't be
    # created automatically if you don't provide one, so you have to either
    # create it manually or via some other chart. The mailpit chart creates it automatically,
    # and then you can just supply the name.
    existingSecret: "ns-notify-smtp"
