## Create a PostgreSQL cluster using the CloudNative-PG operator
## (https://github.com/cloudnative-pg/cloudnative-pg)
##

dbName: notifications
dbUser: notifications_user

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  size: 1Gi
  ## Set storageClass: "" to use cluster default storageClass (e.g. on Rancher Desktop)
  storageClass: csi-cephfs-sc
