package org.dataone.notifications.api.resource;

/**
 * A record containing the string name-value pairs to be returned to the client (e.g. as json)
 * As stated by JEP 395, Records are meant to be "transparent carriers for immutable data". Default
 * constructor, getters, hashCode/equals and toString() will be generated by the compiler. See
 * https://openjdk.org/jeps/395
 *
 * @param subject
 * @param email
 * @param resourceType
 * @param resources
 */
public record HttpGetResponse(
    String subject,
    String email,
    String resourceType,
    String[] resources) {}
