package org.dataone.notifications.api.resource;

/**
 * A record containing the string name-value pairs to be returned to the client (e.g. as json)
 * As stated by JEP 395, Records are meant to be "transparent carriers for immutable data". Default
 * constructor, getters, hashCode/equals and toString() will be generated by the compiler. See
 * https://openjdk.org/jeps/395
 *
 * @param subject The unique identifier for this user (e.g. an orcid or DN), as stored in the
 *                account service
 * @param resourceType Denotes the type of resource the user wants to monitor for changes (e.g. a
 *                    dataset, citations, etc)
 * @param resources An array of zero or more <code>pids</code> of the given
 *                  <code>resourceType</code>, to which this <code>subject</code> is subscribed
 */
public record HttpResponseRecord(
    String subject,
    String resourceType,
    String[] resources) {}
