# This is the main file that defines the CI pipeline for the project using GitHub Actions.
name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "develop"
      - "feature-*"
      - "bugfix-*"
    tags: [ '*.*.*' ]

jobs:
  maven-build:
    uses: ./ci/maven-build.yml

  docker-publish:
    if: github.ref_name == 'develop' || github.ref_name == '*.*.*'
    needs: maven-build
    uses: ./ci/docker-publish.yml
    with:
      version: ${{ needs.maven-build.outputs.version }}
