ns:
  auth:
    api:
      baseUrl: {{ .Values.ns.auth.api.baseUrl | default "https://cn-sandbox.test.dataone.org/cn/v2" }}
      authenticate: {{ .Values.ns.auth.api.authenticate | default "/diag/subject" }}
  database:
    name: {{ .Values.ns.database.dbName | default "notifications" }}
    jdbcHost: {{ required "ns.database.jdbcHost IS REQUIRED" .Values.ns.database.jdbcHost }}
    jdbcPort: {{ default "5432" .Values.ns.database.jdbcPort | quote }}
    ##  See HikariCP configuration options at:
    ##  https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#gear-configuration-knobs-baby
    driverClassName: "org.postgresql.Driver"
